### PR TITLE
fix:  GH-300

### PR DESCRIPTION
**Pull request by nekator**

### CODE REVIEW

**Comment by zzhzero** [comment]
https://gitlab.com/gitlab-org/gitlab/-/issues/15647
Seems to still be a problem
@nekator 
@garethjevans

**Comment by nekator** [comment]
I will look at it today. Maybe make it an interface{} and then type check it to make it an Boolean even if it is "0" or "1"

**Comment by nekator** [comment]
created jenkins-x/go-scm#355

**Pull request merged**
