### PR TITLE
fix: fix failing lighthouse builds

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by ankitm123** [comment]
Lighthouse builds are failing atm with the error:
```
# github.com/jenkins-x/lighthouse/pkg/webhook
--
  |   |   |   | pkg/webhook/events.go:69:16: cannot use ic.Issue.PullRequest (variable of type scm.PullRequest) as type bool in struct literal
  |   |   |   | pkg/webhook/events.go:82:5: non-boolean condition in if statement
  |   |   |   | make: *** [Makefile:76: build-webhooks-linux] Error 2

```

Passing a pointer to a struct, will help in checking if it's nil and determine if it's a PR or not.

**Comment by ankitm123** [comment]
@garethjevans probably worth running integration tests to be sure this works?

**Comment by ankitm123** [comment]
Breaks here: https://github.com/jenkins-x/lighthouse/blob/03e54f647abcd82dc3dd662206e28fb13a1d13df/pkg/webhook/events.go#L69 and https://github.com/jenkins-x/lighthouse/blob/03e54f647abcd82dc3dd662206e28fb13a1d13df/pkg/webhook/events.go#L82

**Comment by garethjevans** [comment]
@ankitm123 thanks for the heads up, i'll get the tests run today

**Pull request merged**
