### PR TITLE
fix: the logic of if skip tls is incorrect

### PR DESCRIPTION
**Pull request by LinuxSuRen**
This issue was caused by https://github.com/jenkins-x/go-scm/pull/363

### CODE REVIEW

**Comment by garethjevans** [comment]
@LinuxSuRen can you take a look at the lint issue?

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen can you take a look at the lint issue?

I want to. But I'm not able to access the link. Is there any way to see the log output? Or, which command I can use to see the lint errors.

**Comment by garethjevans** [comment]
@LinuxSuRen I also can't access that link, but `make lint` should be enough to reproduce locally.  I get:

```
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: goimports: can't extract issues from gofmt diff output "--- /Users/garethjevans/workspace/go-scm/scm/factory/examples/repo/main.go.orig\t2023-01-25 09:30:31\n+++ /Users/garethjevans/workspace/go-scm/scm/factory/examples/repo/main.go\t2023-01-25 09:30:31\n@@ -3,8 +3,9 @@\n import (\n \t\"context\"\n \t\"fmt\"\n-\t\"github.com/jenkins-x/go-scm/scm\"\n \t\"os\"\n+\n+\t\"github.com/jenkins-x/go-scm/scm\"\n \n \t\"github.com/jenkins-x/go-scm/scm/factory\"\n \t\"github.com/jenkins-x/go-scm/scm/factory/examples/helpers\"\n": can't parse patch: parsing time "2023-01-25 09:30:31" as "2006-01-02 15:04:05 -0700": cannot parse "" as "-0700"
```

**Comment by garethjevans** [comment]
But I also get that failure on main too, will investigate.

**Pull request merged**
