### PR TITLE
feat: Bitbucket cloud PR comment support

### PR DESCRIPTION
**Pull request by sushdive**
Enhance bitbucket cloud support in jenkins-x.
* Supports handling of PR comment in bitbucket cloud
* Enables submitting ChatOps commands such as "/retest" on a PR that triggers a pipeline run
Verification of the changes has been done manually

### CODE REVIEW

**Comment by jstrachan** [comment]
could you remove the VERSION and .jx/variables.sh from the commit please? those look to have been added by accident

**Comment by sushdive** [comment]
> could you remove the VERSION and .jx/variables.sh from the commit please? those look to have been added by accident
Sorry for the trouble.
I tried to correct commit.
Please confirm.

Thank you

**Comment by sushdive** [comment]
there seems to be still some issue with the PR.
let me fix it.

**Comment by sushdive** [comment]
fixed commits now.
please review.

**Comment by jstrachan** [comment]
unfortunately lots of unit tests fail now. Could you try `make test` locally to see if you can reproduce it?

```


--- FAIL: TestPullList (0.00s)
--
  |   |   |   | pr_test.go:49: Unexpected Results
  |   |   |   | pr_test.go:50:   []*scm.PullRequest{
  |   |   |   | &{
  |   |   |   | ... // 5 identical fields
  |   |   |   | Ref:    "refs/pull-requests/2/from",
  |   |   |   | Source: "42f383c381d9",
  |   |   |   | - 		Target: "",
  |   |   |   | + 		Target: "ec8d3da80fc5",
  |   |   |   | Base: scm.PullRequestBranch{
  |   |   |   | - 			Ref:  "master",
  |   |   |   | + 			Ref:  "",
  |   |   |   | - 			Sha:  "",
  |   |   |   | + 			Sha:  "ec8d3da80fc5",
  |   |   |   | Repo: scm.Repository{ID: "{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}", Namespace: "jstrachan", Name: "demo6", FullName: "jstrachan/demo6", Clone: "https://bitbucket.org/jstrachan/demo6.git", CloneSSH: "git@bitbucket.org:jstrachan/demo6.git", Link: "https://bitbucket.org/jstrachan/demo6"},
  |   |   |   | },
  |   |   |   | Head: scm.PullRequestBranch{
  |   |   |   | - 			Ref:  "somestuff",
  |   |   |   | + 			Ref:  "",
  |   |   |   | Sha:  "42f383c381d9",
  |   |   |   | Repo: scm.Repository{ID: "{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}", Namespace: "jstrachan", Name: "demo6", FullName: "jstrachan/demo6", Clone: "https://bitbucket.org/jstrachan/demo6.git", CloneSSH: "git@bitbucket.org:jstrachan/demo6.git", Link: "https://bitbucket.org/jstrachan/demo6"},
  |   |   |   | },
  |   |   |   | Fork:  "false",
  |   |   |   | State: "open",
  |   |   |   | ... // 15 identical fields
  |   |   |   | },
  |   |   |   | &{
  |   |   |   | ... // 5 identical fields
  |   |   |   | Ref:    "refs/pull-requests/1/from",
  |   |   |   | Source: "bf9b796a1dd0",
  |   |   |   | - 		Target: "ec8d3da80fc5",
  |   |   |   | + 		Target: "",
  |   |   |   | Base: scm.PullRequestBranch{
  |   |   |   | - 			Ref:  "master",
  |   |   |   | + 			Ref:  "",
  |   |   |   | - 			Sha:  "ec8d3da80fc5",
  |   |   |   | + 			Sha:  "",
  |   |   |   | Repo: scm.Repository{ID: "{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}", Namespace: "jstrachan", Name: "demo6", FullName: "jstrachan/demo6", Clone: "https://bitbucket.org/jstrachan/demo6.git", CloneSSH: "git@bitbucket.org:jstrachan/demo6.git", Link: "https://bitbucket.org/jstrachan/demo6"},
  |   |   |   | },
  |   |   |   | Head: scm.PullRequestBranch{
  |   |   |   | - 			Ref:  "cheese",
  |   |   |   | + 			Ref:  "",
  |   |   |   | Sha:  "bf9b796a1dd0",
  |   |   |   | Repo: scm.Repository{ID: "{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}", Namespace: "jstrachan", Name: "demo6", FullName: "jstrachan/demo6", Clone: "https://bitbucket.org/jstrachan/demo6.git", CloneSSH: "git@bitbucket.org:jstrachan/demo6.git", Link: "https://bitbucket.org/jstrachan/demo6"},
  |   |   |   | },
  |   |   |   | Fork:  "false",
  |   |   |   | State: "open",
  |   |   |   | ... // 15 identical fields
  |   |   |   | },
  |   |   |   | }
  |   |   |   |  
  |   |   |   | pr_test.go:53: got JSON: [{"Number":2,"Title":"added awesome to Jenkinsfile","Body":"","Labels":null,"Sha":"42f383c381d9","Ref":"refs/pull-requests/2/from","Source":"42f383c381d9","Target":"","Base":{"Ref":"master","Sha":"","Repo":{"ID":"{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}","Namespace":"jstrachan","Name":"demo6","FullName":"jstrachan/demo6","Perm":null,"Branch":"","Private":false,"Archived":false,"Clone":"https://bitbucket.org/jstrachan/demo6.git","CloneSSH":"git@bitbucket.org:jstrachan/demo6.git","Link":"https://bitbucket.org/jstrachan/demo6","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"}},"Head":{"Ref":"somestuff","Sha":"42f383c381d9","Repo":{"ID":"{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}","Namespace":"jstrachan","Name":"demo6","FullName":"jstrachan/demo6","Perm":null,"Branch":"","Private":false,"Archived":false,"Clone":"https://bitbucket.org/jstrachan/demo6.git","CloneSSH":"git@bitbucket.org:jstrachan/demo6.git","Link":"https://bitbucket.org/jstrachan/demo6","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"}},"Fork":"false","State":"open","Closed":false,"Draft":false,"Merged":false,"Mergeable":false,"Rebaseable":false,"MergeableState":"","MergeSha":"","Author":{"ID":0,"Login":"","Name":"James Strachan","Email":"","Avatar":"https://secure.gravatar.com/avatar/64dbbbeb960d4014b28cd64d73340d94?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FJS-3.png","Link":"https://api.bitbucket.org/2.0/users/%7B9c09f561-6d19-4635-8d6f-5eb06fed3a08%7D","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"},"Assignees":null,"Reviewers":null,"Milestone":{"Number":0,"ID":0,"Title":"","Description":"","Link":"","State":"","DueDate":null},"Created":"2018-04-21T08:56:02.020408Z","Updated":"2018-04-21T09:01:57.659051Z","Link":"https://bitbucket.org/jstrachan/demo6/pull-requests/2","DiffLink":"https://api.bitbucket.org/2.0/repositories/jstrachan/demo6/diff/jstrachan/demo6:42f383c381d9%0Dec8d3da80fc5?from_pullrequest_id=2"},{"Number":1,"Title":"added awesome","Body":"","Labels":null,"Sha":"bf9b796a1dd0","Ref":"refs/pull-requests/1/from","Source":"bf9b796a1dd0","Target":"ec8d3da80fc5","Base":{"Ref":"master","Sha":"ec8d3da80fc5","Repo":{"ID":"{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}","Namespace":"jstrachan","Name":"demo6","FullName":"jstrachan/demo6","Perm":null,"Branch":"","Private":false,"Archived":false,"Clone":"https://bitbucket.org/jstrachan/demo6.git","CloneSSH":"git@bitbucket.org:jstrachan/demo6.git","Link":"https://bitbucket.org/jstrachan/demo6","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"}},"Head":{"Ref":"cheese","Sha":"bf9b796a1dd0","Repo":{"ID":"{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}","Namespace":"jstrachan","Name":"demo6","FullName":"jstrachan/demo6","Perm":null,"Branch":"","Private":false,"Archived":false,"Clone":"https://bitbucket.org/jstrachan/demo6.git","CloneSSH":"git@bitbucket.org:jstrachan/demo6.git","Link":"https://bitbucket.org/jstrachan/demo6","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"}},"Fork":"false","State":"open","Closed":false,"Draft":false,"Merged":false,"Mergeable":false,"Rebaseable":false,"MergeableState":"","MergeSha":"","Author":{"ID":0,"Login":"","Name":"James Strachan","Email":"","Avatar":"https://secure.gravatar.com/avatar/64dbbbeb960d4014b28cd64d73340d94?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FJS-3.png","Link":"https://api.bitbucket.org/2.0/users/%7B9c09f561-6d19-4635-8d6f-5eb06fed3a08%7D","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"},"Assignees":null,"Reviewers":null,"Milestone":{"Number":0,"ID":0,"Title":"","Description":"","Link":"","State":"","DueDate":null},"Created":"2018-04-18T14:07:40.354351Z","Updated":"2018-04-20T16:28:21.843691Z","Link":"https://bitbucket.org/jstrachan/demo6/pull-requests/1","DiffLink":"https://api.bitbucket.org/2.0/repositories/jstrachan/demo6/diff/jstrachan/demo6:bf9b796a1dd0%0Dec8d3da80fc5?from_pullrequest_id=1"}]
  |   |   |   | --- FAIL: TestPullCreate (0.00s)
  |   |   |   | pr_test.go:125: Unexpected Results
  |   |   |   | pr_test.go:126:   &scm.PullRequest{
  |   |   |   | ... // 5 identical fields
  |   |   |   | Ref:    "refs/pull-requests/2/from",
  |   |   |   | Source: "42f383c381d9",
  |   |   |   | - 	Target: "",
  |   |   |   | + 	Target: "ec8d3da80fc5",
  |   |   |   | Base: scm.PullRequestBranch{
  |   |   |   | - 		Ref:  "master",
  |   |   |   | + 		Ref:  "",
  |   |   |   | - 		Sha:  "",
  |   |   |   | + 		Sha:  "ec8d3da80fc5",
  |   |   |   | Repo: scm.Repository{ID: "{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}", Namespace: "jstrachan", Name: "demo6", FullName: "jstrachan/demo6", Clone: "https://bitbucket.org/jstrachan/demo6.git", CloneSSH: "git@bitbucket.org:jstrachan/demo6.git", Link: "https://bitbucket.org/jstrachan/demo6"},
  |   |   |   | },
  |   |   |   | Head: scm.PullRequestBranch{
  |   |   |   | - 		Ref:  "somestuff",
  |   |   |   | + 		Ref:  "",
  |   |   |   | Sha:  "42f383c381d9",
  |   |   |   | Repo: scm.Repository{ID: "{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}", Namespace: "jstrachan", Name: "demo6", FullName: "jstrachan/demo6", Clone: "https://bitbucket.org/jstrachan/demo6.git", CloneSSH: "git@bitbucket.org:jstrachan/demo6.git", Link: "https://bitbucket.org/jstrachan/demo6"},
  |   |   |   | },
  |   |   |   | Fork:  "false",
  |   |   |   | State: "open",
  |   |   |   | ... // 15 identical fields
  |   |   |   | }
  |   |   |   |  
  |   |   |   | pr_test.go:129: generated {"Number":2,"Title":"added awesome to Jenkinsfile","Body":"","Labels":null,"Sha":"42f383c381d9","Ref":"refs/pull-requests/2/from","Source":"42f383c381d9","Target":"","Base":{"Ref":"master","Sha":"","Repo":{"ID":"{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}","Namespace":"jstrachan","Name":"demo6","FullName":"jstrachan/demo6","Perm":null,"Branch":"","Private":false,"Archived":false,"Clone":"https://bitbucket.org/jstrachan/demo6.git","CloneSSH":"git@bitbucket.org:jstrachan/demo6.git","Link":"https://bitbucket.org/jstrachan/demo6","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"}},"Head":{"Ref":"somestuff","Sha":"42f383c381d9","Repo":{"ID":"{b7c5a1c5-28bb-4e20-b262-3beaff0dd827}","Namespace":"jstrachan","Name":"demo6","FullName":"jstrachan/demo6","Perm":null,"Branch":"","Private":false,"Archived":false,"Clone":"https://bitbucket.org/jstrachan/demo6.git","CloneSSH":"git@bitbucket.org:jstrachan/demo6.git","Link":"https://bitbucket.org/jstrachan/demo6","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"}},"Fork":"false","State":"open","Closed":false,"Draft":false,"Merged":false,"Mergeable":false,"Rebaseable":false,"MergeableState":"","MergeSha":"","Author":{"ID":0,"Login":"","Name":"James Strachan","Email":"","Avatar":"https://secure.gravatar.com/avatar/64dbbbeb960d4014b28cd64d73340d94?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FJS-3.png","Link":"https://api.bitbucket.org/2.0/users/%7B9c09f561-6d19-4635-8d6f-5eb06fed3a08%7D","Created":"0001-01-01T00:00:00Z","Updated":"0001-01-01T00:00:00Z"},"Assignees":null,"Reviewers":null,"Milestone":{"Number":0,"ID":0,"Title":"","Description":"","Link":"","State":"","DueDate":null},"Created":"2018-04-21T08:56:02.020408Z","Updated":"2018-04-21T09:01:57.659051Z","Link":"https://bitbucket.org/jstrachan/demo6/pull-requests/2","DiffLink":"https://api.bitbucket.org/2.0/repositories/jstrachan/demo6/diff/jstrachan/demo6:42f383c381d9%0Dec8d3da80fc5?from_pullrequest_id=2"}
  |   |   |   | FAIL
```

**Comment by sushdive** [comment]
checking failed tests now

**Pull request merged**
