### PR TITLE
refactor: upgrade go version to 1.17

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
would you mind telling us why do you want to upgrade the golang version?

**Comment by ankitm123** [comment]
> would you mind telling us why do you want to upgrade the golang version?

From go release docs:
```
Each major Go release is supported until there are two newer major releases
```
Source: https://go.dev/doc/devel/release (ofc they will patch security fixes)
We are using an old version of go, there seems no reason to stick to it, with go 1.18 (that will put us 3 versions behind) coming out in a few months (with support for generics). 
There are performance improvements that come with every version of golang, and we dont want to be stuck on an older version and then have to upgrade with less time for testing (we are a bit thinner on the test coverage, so need more time to be sure that things are stable after moving to 1.17).

Also, given the amount of repositories that Jenkins X has, it will take atleast a month or 2 to upgrade everything to go 1.17, and even longer to test it out enough.

Having said that, the priority for no now is to lint the entire codebase, and then pick up the upgrade.

/hold

**Comment by ankitm123** [comment]
/close
superseded by #322

**Pull request closed without merging**
