### PR TITLE
feat: Add support for creating PullRequests.

### PR DESCRIPTION
**Pull request by bigkevmcd**
This adds support for creating a PullRequest with title, body branch references in the GitHub and GitLab drivers.
    
The fake driver records created PullRequestInput records.
    
The other drivers return NotSupported errors.

### CODE REVIEW

**Comment by abayer** [comment]
@bigkevmcd Sorry to bug you, but have you actually tested the PR creation on gitlab? I have a sinking feeling it won't do anything - https://github.com/jenkins-x/go-scm/blob/679648236f01986dd46710eb57a2d4403441c0c1/scm/driver/gitlab/gitlab.go#L58 doesn't actually pass `in` to the request, which...yeah, that'll be a problem. =) I'll play around with it on #68, where I'm adding updating PRs, but I think we need to do something more like https://github.com/jenkins-x/go-scm/blob/b82884a2577cb937b5ddc20fec1b640970ff9d3e/scm/driver/gitlab/issue.go#L83-L85.

I'm legitimately not sure why we're encoding as parameters rather than just passing as data with `application/json` in general for Gitlab, but if that works, it's fine by me. =)

**Comment by bigkevmcd** [comment]
@abayer sorry, I was travelling last week.

I tested the GitHub version, but alas, I didn't test the GitLab one, and naively assumed that the tests would cover it, dunno why I didn't test it givn that it was a 2 line change to run the code against GitLab, and yes, it responds with a 400.

I'm happy to rework the implementation to convert to JSON, which is what it should be doing, yes.

**Comment by abayer** [comment]
No worries! I'm traveling this week, so my responses won't be timely either. =) I've started reworking the gl web hook stuff completely - no rush on the GL api side from my perspective. It feels like a lot of the GL code was copied loosely from somewhere else without fully implementing everything, let alone testing it, so I don't expect this is gonna be speedy.

**Comment by abayer** [comment]
Oh, and at least it's not BitBucket. Sigh.

**Pull request merged**
