### PR TITLE
fix: unable to build locally

### PR DESCRIPTION
**Pull request by garethjevans**
Locally I was unable to build this without updating the sys pacakge.

### CODE REVIEW

**Comment by ankitm123** [comment]
Weird, I was able to build it without changing updating the sys package :confused: Which version of go are u using?

**Comment by garethjevans** [comment]
`go version go1.18.6 darwin/amd64`

**Comment by garethjevans** [comment]
@ankitm123 without the change I get 

```
❯ make test
go test ./...
ok  	github.com/jenkins-x/go-scm/pkg/hmac	(cached)
# golang.org/x/sys/unix
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:136:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:151:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:166:3: //go:linkname must refer to declared function or variable
../../.asdf/installs/golang/1.18.6/packages/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_amd64.go:166:3: too many errors
FAIL	github.com/jenkins-x/go-scm/scm [build failed]
ok  	github.com/jenkins-x/go-scm/scm/driver/bitbucket	(cached)
ok  	github.com/jenkins-x/go-scm/scm/driver/fake	(cached)
ok  	github.com/jenkins-x/go-scm/scm/driver/gitea	(cached)
FAIL	github.com/jenkins-x/go-scm/scm/driver/github [build failed]
FAIL	github.com/jenkins-x/go-scm/scm/driver/github/integration [build failed]
ok  	github.com/jenkins-x/go-scm/scm/driver/gitlab	(cached)
ok  	github.com/jenkins-x/go-scm/scm/driver/gitlab/integration	(cached)
ok  	github.com/jenkins-x/go-scm/scm/driver/gogs	(cached)
?   	github.com/jenkins-x/go-scm/scm/driver/internal/null	[no test files]
ok  	github.com/jenkins-x/go-scm/scm/driver/stash	(cached)
FAIL	github.com/jenkins-x/go-scm/scm/factory [build failed]
ok  	github.com/jenkins-x/go-scm/scm/transport	(cached)
ok  	github.com/jenkins-x/go-scm/scm/transport/internal	(cached)
ok  	github.com/jenkins-x/go-scm/scm/transport/oauth1	(cached)
ok  	github.com/jenkins-x/go-scm/scm/transport/oauth2	(cached)
make: *** [test] Error 2
 ```

**Comment by waciumawanjohi** [comment]
I had the same experience:
`go version go1.19.1 darwin/arm64`

When I ran `go install ./...` on `main` I had the following:
```
# golang.org/x/sys/unix
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:136:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:151:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:166:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190616124812-15dcb6c0061f/unix/zsyscall_darwin_arm64.go:166:3: too many errors
```

Running with the changes in this pr, `go install ./...` and `go test ./...` both succeeded.

**Comment by ankitm123** [comment]
I see, the reason i cant reproduce this issue is because I am using Linux amd64 version, and everything just works. The pipeline also uses the same linux servers, so they also don't catch it.

**Review by ankitm123 — APPROVED** [review]

**Comment by garethjevans** [comment]
thanks @ankitm123

**Pull request merged**
