### PR TITLE
fix: generate release link instead of using the API link that gitea provides

### PR DESCRIPTION
**Pull request by cameronbraid**

### CODE REVIEW

**Comment by jstrachan** [comment]
@cameronbraid looks like lint failed...

```
LINTING
/home/jenkins/go/bin/golint -set_exit_status ./...
scm/driver/gitea/release.go:132:6: func ConvertApiUrlToHtmlUrl should be ConvertAPIURLToHTMLURL
scm/driver/gitea/release.go:132:29: func parameter apiUrl should be apiURL
```

**Comment by cameronbraid** [comment]
yeah lint - thats much easier to read

**Pull request merged**
