### PR TITLE
Add modifiy field in changes APIs in Bitbucket server (stash)

### PR DESCRIPTION
**Pull request by zakisk**
file's modification status is missing in response of Pull Request changes and commit changes APIs. this PR addresses that issue in Bitbucket server (stash).

### CODE REVIEW

**Comment by msvticket** [comment]
What is this PR needed for?

**Comment by zakisk** [comment]
@msvticket in [tekton Pipelines as Code](https://github.com/openshift-pipelines/pipelines-as-code), we need it to list changes of a commit or PR in Bitbucket server. but I saw that it lacks for modified files.

**Comment by msvticket** [comment]
> @msvticket in [tekton Pipelines as Code](https://github.com/openshift-pipelines/pipelines-as-code), we need it to list changes of a commit or PR in Bitbucket server. but I saw that it lacks for modified files.

So you mean that you are about to start using jenkins-x/go-scm in pipelines-as-code? I don't see that jenkins-x/go-scm is currently used in the project.

**Comment by zakisk** [comment]
@msvticket at the moment we use [go-bitbucket](github.com/gfleury/go-bitbucket-v1) but seems that it is not well maintained and buggy (in some endpoints) so we're planning to replace it with jenkins-x/go-scm

**Comment by zakisk** [comment]
> > @msvticket in [tekton Pipelines as Code](https://github.com/openshift-pipelines/pipelines-as-code), we need it to list changes of a commit or PR in Bitbucket server. but I saw that it lacks for modified files.
> 
> So you mean that you are about to start using jenkins-x/go-scm in pipelines-as-code? I don't see that jenkins-x/go-scm is currently used in the project.

@msvticket  yes, I was just typing reply :slightly_smiling_face:

**Comment by zakisk** [comment]
@msvticket and I am gonna raise some more PRs in future.

**Comment by msvticket** [comment]
I see. Just to manage your expectations: go-scm is currently only maintained as much as is needed by Jenkins X applications, mainly [lighthouse](https://github.com/jenkins-x/lighthouse). That said: If you are willing to continue like this and create PRs for functionality missing for you and pinging us to review then that is certainly fine by us.

**Comment by zakisk** [comment]
> I see. Just to manage your expectations: go-scm is currently only maintained as much as is needed by Jenkins X applications, mainly [lighthouse](https://github.com/jenkins-x/lighthouse). That said: If you are willing to continue like this and create PRs for functionality missing for you and pinging us to review then that is certainly fine by us.

@msvticket thank you so much, I will prepare my PRs and raise so that we can finish them in less time and expect your attention ASAP thanks again.

**Comment by zakisk** [comment]
@msvticket can you please make this /ok-to-test?

**Pull request merged**
