### PR TITLE
feat: implement stash.PullRequestService.ListComments

### PR DESCRIPTION
**Pull request by wbrefvem**
This is a first spike at implementing ListComments for Bitbucket Server PRs

### CODE REVIEW

**Comment by jstrachan** [comment]
@wbrefvem it'd be good to add tests for this like the rest of go-scm does. 
e.g. I added this test for ListTeams on github:
https://github.com/jenkins-x/go-scm/blob/master/scm/driver/github/org_test.go#L83-116

you then add some real json from the git provider:
https://github.com/jenkins-x/go-scm/blob/master/scm/driver/github/testdata/teams.json
and provide the expected json: https://github.com/jenkins-x/go-scm/blob/master/scm/driver/github/testdata/teams.json.golden

works pretty nicely

**Comment by wbrefvem** [comment]
@jstrachan ah yes, meant to do that before raising this.

**Comment by jstrachan** [comment]
@wbrefvem gonna merge, but would love another PR with the unit test later!

**Pull request merged**
