### PR TITLE
fix: github enterprise graphql endpoint url

### LINKED ISSUE #31: graphql endpoint for Github Enterprise is incorrect
The endpoint should be: `http(s)://[hostname]/api/graphql`

The currently produced endpoint is: `http(s)://[hostname]/api/v3/graphql`

See: https://developer.github.com/enterprise/2.18/v4/guides/forming-calls/#the-graphql-endpoint

### PR DESCRIPTION
**Pull request by hugoduncan**
Exposes Client.GraphQLURL to enable testing.

fixes #31

### CODE REVIEW

**Comment by hugoduncan** [comment]
@jstrachan how do I help get this into a lighthouse/tide release?

**Comment by hugoduncan** [comment]
iiuc, it gets picked up automatically when lighthouse is built, so I can just set the image tag for tide in my values.xml.

**Comment by jstrachan** [comment]
ah its looking like the automated PRs on lighthouse were not working - fixed!
https://github.com/jenkins-x/lighthouse/pull/183

**Comment by jstrachan** [comment]
@hugoduncan the new lighthouse image should be released in the next hour or so here: https://gcr.io/jenkinsxio/lighthouse so you can just manually tweak your `tide` deployment - the new lighthouse version should get merged into the version stream in the next 24-48 hours: https://jenkins-x.io/docs/concepts/version-stream/

**Pull request merged**
